config/routes.rb
Rails.application.routes.draw do
  get 'fases/canvi_fase'
  resources :missatges
  devise_for :users
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/missatge.rb
class Missatge < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def name
    [first_name, last_name].compact.join(' ')
  end

  validates :first_name, :presence => true
  validates :last_name, :presence => true

  def self.online
    ids = ActionCable.server.pubsub.redis_connection_for_subscriptions.smembers "online"
    where(id: ids)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
  
end

app/controllers/fases_controller.rb
class FasesController < ApplicationController
	layout 'enblanc'
  
  def canvi_fase
  	ActionCable.server.broadcast "stage_channel", stage_id: params[:fase]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  
  def index
  	@missatge = Missatge.new
    @missatges = Missatge.all
    @video = 'wHiat6z6W00dCJjlnoLnx5Fln2mzR9bnuWRIlHeSjZ01E'
  end
end

app/controllers/missatges_controller.rb
class MissatgesController < ApplicationController
  before_action :set_missatge, only: [:show, :edit, :update, :destroy]

  # GET /missatges
  # GET /missatges.json
  def index
    @missatges = Missatge.all
  end

  # GET /missatges/1
  # GET /missatges/1.json
  def show
  end

  # GET /missatges/new
  def new
    @missatge = Missatge.new
  end

  # GET /missatges/1/edit
  def edit
  end

  # POST /missatges
  # POST /missatges.json
  def create
    @missatge = Missatge.create(missatge_params)
    if @missatge.save
      ActionCable.server.broadcast "room_channel", user_id: @missatge.user_id, nom: current_user.first_name, contingut: @missatge.contingut
    else
    end
  end

  # PATCH/PUT /missatges/1
  # PATCH/PUT /missatges/1.json
  def update
    respond_to do |format|
      if @missatge.update(missatge_params)
        format.html { redirect_to @missatge, notice: 'Missatge was successfully updated.' }
        format.json { render :show, status: :ok, location: @missatge }
      else
        format.html { render :edit }
        format.json { render json: @missatge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /missatges/1
  # DELETE /missatges/1.json
  def destroy
    @missatge.destroy
    respond_to do |format|
      format.html { redirect_to missatges_url, notice: 'Missatge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_missatge
      @missatge = Missatge.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def missatge_params
      params.require(:missatge).permit(:user_id, :contingut)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fases_helper.rb
module FasesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/missatges_helper.rb
module MissatgesHelper
end

app/views/fases/_cinquena.html.erb
<div id="container-fase-5" class="container-fase">
	<h1 class="titol-repte">Estufa o manta?</h1>
	<p>Sou a casa i teniu fred. Si no voleu consumir energia què trieu per escalfar-vos?</p>
	<div class="container-manta">
		<%= image_tag "manta.jpg", class: "estufa-manta", id: "tria-manta" %>
		<%= image_tag "pau.jpg", class: "estufa-manta", id: "tria-pau" %>
		<%= image_tag "estufa.jpg", class: "estufa-manta", id: "tria-estufa" %>
	</div>
	<div class="container-clear"></div>
	<p class="benfet5">Correcte!</p>
  <p class="malfet5">No és correcte</p>
</div>

app/views/fases/_desena.html.erb
<div id="container-fase-10" class="container-fase">
	<h1 class="titol-repte">Tria la millor opció per estalviar energia</h1>
	<p>Podem estalviar molta energia amb les petites decisions que prenem cada dia!</p>
	
	<div id="container-tria-aventura-1">
		<div class="item-tria-aventura">
			<div class="text-tria-aventura">
				<p>En Joan engega tots els llums</p>
			</div>
			<%= image_tag "llum_artificial.jpg", class: "tria-aventura", id: "llum-artificial" %>
			
		</div>
		<div class="item-tria-aventura">
			<div class="text-tria-aventura">
				<p>En Joan aprofita la llum del Sol</p>
			</div>
			<%= image_tag "llum_natural.jpg", class: "tria-aventura", id: "llum-natural" %>
			
		</div>
	</div>

	<div id="container-tria-aventura-2">
		<div class="item-tria-aventura">
			<div class="text-tria-aventura">
				<p>La Paula agafa ràpid el que necessita i torna a tancar la nevera</p>
			</div>
			<%= image_tag "nevera_be.jpg", class: "tria-aventura", id: "nevera-be" %>
			
		</div>
		<div class="item-tria-aventura">
			<div class="text-tria-aventura">
				<p>La Paula deixa la nevera oberta molta estona mentre decideix què vol agafar</p>
			</div>
			<%= image_tag "nevera_malament.jpg", class: "tria-aventura", id: "nevera-malament" %>
			
		</div>
	</div>

	<div id="container-tria-aventura-3">
		<div class="item-tria-aventura">
			<div class="text-tria-aventura">
				<p>La Marta va poc abrigada i han de pujar la calefacció a l'escola</p>
			</div>
			<%= image_tag "classe_fred.jpg", class: "tria-aventura", id: "classe-fred" %>
			
		</div>
		<div class="item-tria-aventura">
			<div class="text-tria-aventura">
				<p>La Marta va ben vestida per no tenir fred encara que sigui hivern</p>
			</div>
			<%= image_tag "classe_be.jpg", class: "tria-aventura", id: "classe-be" %>
			
		</div>
	</div>

	<div id="container-tria-aventura-4">
		<div class="item-tria-aventura">
			<div class="text-tria-aventura">
				<p>L'Anna torna de la feina amb el cotxe</p>
			</div>
			<%= image_tag "transport_cotxe.jpg", class: "tria-aventura", id: "transport-cotxe" %>
			
		</div>
		<div class="item-tria-aventura">
			<div class="text-tria-aventura">
				<p>L'Anna torna de la feina amb la bicicleta</p>
			</div>
			<%= image_tag "transport_bici.jpg", class: "tria-aventura", id: "transport-bici" %>
			
		</div>
	</div>

	<div id="container-tria-aventura-5">
		<div class="item-tria-aventura">
			<div class="text-tria-aventura">
				<p>Després de rentar la roba l'estén per que s'assequi</p>
			</div>
			<%= image_tag "roba_estesa.jpg", class: "tria-aventura", id: "roba-estesa" %>
			
		</div>
		<div class="item-tria-aventura">
			<div class="text-tria-aventura">
				<p>Després de rentar la roba la posa a l'assecadora</p>
			</div>
			<%= image_tag "roba_assecadora.jpg", class: "tria-aventura", id: "roba-assecadora" %>
			
		</div>
	</div>
</div>

app/views/fases/_indefinida.html.erb
<div id="container-fase-2" class="container-fase">
	<ul id="sortable">
	  <li class="ui-state-default">1</li>
	  <li class="ui-state-default">2</li>
	  <li class="ui-state-default">3</li>
	  <li class="ui-state-default">4</li>
	  <li class="ui-state-default">5</li>
	  <li class="ui-state-default">6</li>
	  <li class="ui-state-default">7</li>
	  <li class="ui-state-default">8</li>
	  <li class="ui-state-default">9</li>
	  <li class="ui-state-default">10</li>
	  <li class="ui-state-default">11</li>
	  <li class="ui-state-default">12</li>
	</ul>
</div>

app/views/fases/_primera.html.erb
<div id="container-fase-1" class="container-fase">
  <h1 class="titol-repte">El repte de les lletres perdudes</h1>
  <br/>
  <p class="text-repte">Per què és important estalviar energia a casa?</p>
  <p id="frase-1" class="repte-lletres-perdudes">P_r _st_lv__r d_n_rs _ ll__t_r c_ntr_ _l c_nv_ cl_m_t_c.</p>
  <p id="frase-2" class="repte-lletres-perdudes">P_r _st<span class="vocal">a</span>lv_<span class="vocal">a</span>r d_n_rs _ ll__t<span class="vocal">a</span>r c_ntr<span class="vocal">a</span> _l c<span class="vocal">a</span>nv_ cl_m<span class="vocal">à</span>t_c.</p>
  <button id="pista-1" class="btn boto-accio">Necessito una pista</button>

  <br/>
  <br/>
  <p class="text-repte">Escriu la resposta aquí:</p>
  <input id="input-repte-1"></input>
  <button id="comprova-repte-1" class="btn boto-accio">Comprova</button>
  <p class="benfet">Correcte!</p>
  <p class="malfet">No és correcte</p>
</div>

app/views/fases/_quarta.html.erb
<div id="container-fase-4" class="container-fase">
	<h1 class="titol-repte">Quina és la pitjor casa?</h1>
	<p>Aquesta pregunta no té una resposta clara, depèn del que considerem important. <br/>Tria la casa que necessita més energia per a ser construïda.</p>
	<div class="container-tres-porquets">
		<%= image_tag "casa_tres_porquets_01.jpg", class: "casa-tres-porquets", id: "porquets-casa-palla" %>
		<%= image_tag "casa_tres_porquets_02.jpg", class: "casa-tres-porquets", id: "porquets-casa-fusta" %>
		<%= image_tag "casa_tres_porquets_03.jpg", class: "casa-tres-porquets", id: "porquets-casa-maons" %>
	</div>
	<div class="container-clear"></div>
	<p class="benfet4">Correcte!</p>
  <p class="malfet4">No és correcte</p>
</div>

app/views/fases/_segona.html.erb
<div id="container-fase-2" class="container-fase">
	<h1 class="titol-repte">On és l'illa de Pasqua?</h1>
	<p>Passa el ratolí per sobre els requadres per trobar l'illa de Pasqua:</p>
	<div class="slice-map-container">
		<div class="slice-row">
			<%= image_tag "mapa_mon_01.jpg", class: "map-slice", id: "map1" %>
			<%= image_tag "mapa_mon_02.jpg", class: "map-slice", id: "map2" %>
			<%= image_tag "mapa_mon_03.jpg", class: "map-slice", id: "map3" %>
			<%= image_tag "mapa_mon_04.jpg", class: "map-slice", id: "map4" %>
			<%= image_tag "mapa_mon_05.jpg", class: "map-slice", id: "map5" %>
			<%= image_tag "mapa_mon_06.jpg", class: "map-slice", id: "map6" %>
			<%= image_tag "mapa_mon_07.jpg", class: "map-slice", id: "map7" %>
			<%= image_tag "mapa_mon_08.jpg", class: "map-slice", id: "map8" %>
			<%= image_tag "mapa_mon_09.jpg", class: "map-slice", id: "map9" %>
			<%= image_tag "mapa_mon_10.jpg", class: "map-slice", id: "map10" %>
		</div>
		<div class="slice-row">
			<%= image_tag "mapa_mon_11.jpg", class: "map-slice", id: "map11" %>
			<%= image_tag "mapa_mon_12.jpg", class: "map-slice", id: "map12" %>
			<%= image_tag "mapa_mon_13.jpg", class: "map-slice", id: "map13" %>
			<%= image_tag "mapa_mon_14.jpg", class: "map-slice", id: "map14" %>
			<%= image_tag "mapa_mon_15.jpg", class: "map-slice", id: "map15" %>
			<%= image_tag "mapa_mon_16.jpg", class: "map-slice", id: "map16" %>
			<%= image_tag "mapa_mon_17.jpg", class: "map-slice", id: "map17" %>
			<%= image_tag "mapa_mon_18.jpg", class: "map-slice", id: "map18" %>
			<%= image_tag "mapa_mon_19.jpg", class: "map-slice", id: "map19" %>
			<%= image_tag "mapa_mon_20.jpg", class: "map-slice", id: "map20" %>
		</div>
		<div class="slice-row">
			<%= image_tag "mapa_mon_21.jpg", class: "map-slice", id: "map21" %>
			<%= image_tag "mapa_mon_22.jpg", class: "map-slice", id: "map22" %>
			<%= image_tag "mapa_mon_23.jpg", class: "map-slice", id: "map23" %>
			<%= image_tag "mapa_mon_24.jpg", class: "map-slice", id: "map24" %>
			<%= image_tag "mapa_mon_25.jpg", class: "map-slice", id: "map25" %>
			<%= image_tag "mapa_mon_26.jpg", class: "map-slice", id: "map26" %>
			<%= image_tag "mapa_mon_27.jpg", class: "map-slice", id: "map27" %>
			<%= image_tag "mapa_mon_28.jpg", class: "map-slice", id: "map28" %>
			<%= image_tag "mapa_mon_29.jpg", class: "map-slice", id: "map29" %>
			<%= image_tag "mapa_mon_30.jpg", class: "map-slice", id: "map30" %>
		</div>
		<div class="slice-row">
			<%= image_tag "mapa_mon_31.jpg", class: "map-slice", id: "map31" %>
			<%= image_tag "mapa_mon_32.jpg", class: "map-slice", id: "map32" %>
			<%= image_tag "mapa_mon_33.jpg", class: "map-slice", id: "map33" %>
			<%= image_tag "mapa_mon_34.jpg", class: "map-slice", id: "map34" %>
			<%= image_tag "mapa_mon_35.jpg", class: "map-slice", id: "map35" %>
			<%= image_tag "mapa_mon_36.jpg", class: "map-slice", id: "map36" %>
			<%= image_tag "mapa_mon_37.jpg", class: "map-slice", id: "map37" %>
			<%= image_tag "mapa_mon_38.jpg", class: "map-slice", id: "map38" %>
			<%= image_tag "mapa_mon_39.jpg", class: "map-slice", id: "map39" %>
			<%= image_tag "mapa_mon_40.jpg", class: "map-slice", id: "map40" %>
		</div>
		<div class="slice-row">
			<%= image_tag "mapa_mon_41.jpg", class: "map-slice", id: "map41" %>
			<%= image_tag "mapa_mon_42.jpg", class: "map-slice", id: "map42" %>
			<%= image_tag "mapa_mon_43.jpg", class: "map-slice", id: "map43" %>
			<%= image_tag "mapa_mon_44.jpg", class: "map-slice", id: "map44" %>
			<%= image_tag "mapa_mon_45.jpg", class: "map-slice", id: "map45" %>
			<%= image_tag "mapa_mon_46.jpg", class: "map-slice", id: "map46" %>
			<%= image_tag "mapa_mon_47.jpg", class: "map-slice", id: "map47" %>
			<div class="background-pasqua"><%= image_tag "mapa_mon_48.jpg", class: "map-slice", id: "map48" %></div>
			<%= image_tag "mapa_mon_49.jpg", class: "map-slice", id: "map49" %>
			<%= image_tag "mapa_mon_50.jpg", class: "map-slice", id: "map50" %>
		</div>
		<div class="slice-row">
			<%= image_tag "mapa_mon_51.jpg", class: "map-slice", id: "map51" %>
			<%= image_tag "mapa_mon_52.jpg", class: "map-slice", id: "map52" %>
			<%= image_tag "mapa_mon_53.jpg", class: "map-slice", id: "map53" %>
			<%= image_tag "mapa_mon_54.jpg", class: "map-slice", id: "map54" %>
			<%= image_tag "mapa_mon_55.jpg", class: "map-slice", id: "map55" %>
			<%= image_tag "mapa_mon_56.jpg", class: "map-slice", id: "map56" %>
			<%= image_tag "mapa_mon_57.jpg", class: "map-slice", id: "map57" %>
			<%= image_tag "mapa_mon_58.jpg", class: "map-slice", id: "map58" %>
			<%= image_tag "mapa_mon_59.jpg", class: "map-slice", id: "map59" %>
			<%= image_tag "mapa_mon_60.jpg", class: "map-slice", id: "map60" %>
		</div>
	</div>
	<div class="slice-row">
		<p class="benfet2">Correcte!</p>
		<p class="malfet2">No és correcte</p>
	</div>
</div>

app/views/fases/_tercera.html.erb
<div id="container-fase-3" class="container-fase">
	<h1 class="titol-repte">De què estan fetes les cases?</h1>
	<p>Col·loqueu sota cada casa el material principal del que està feta</p>
	<div class="container-casa-material" id="casa-material-1">
		<div class="imatge-casa-material">
			<%= image_tag "casa_iglu.jpg", class: "casa-material", id: "casa-iglu" %>
			<p></p>
		</div>
	</div>
	<div class="container-casa-material" id="casa-material-2">
		<div class="imatge-casa-material">
			<%= image_tag "casa_fusta.jpg", class: "casa-material", id: "casa-fusta" %>
			<p></p>
		</div>
	</div>
	<div class="container-casa-material" id="casa-material-3">
		<div class="imatge-casa-material">
			<%= image_tag "casa_terra.jpg", class: "casa-material", id: "casa-terra" %>
		</div>
	</div>
	<div class="container-casa-material" id="casa-material-4">
		<div class="imatge-casa-material">
			<%= image_tag "casa_iurta.jpg", class: "casa-material", id: "casa-iurta" %>
		</div>
	</div>
	<div class="container-casa-material" id="casa-material-5">
		<div class="imatge-casa-material">
			<%= image_tag "casa_pedra.jpg", class: "casa-material", id: "casa-pedra" %>
		</div>
	</div>

	<div class="container-casa-material-clear"></div>

	<div class="container-materials">
		<div id="material-1" class="requadre-material">
		  <div class="text-material">Vidre</div>
		  <%= image_tag "material_vidre.jpg", class: "imatge-material" %>
		</div>
		<div id="material-2" class="requadre-material">
		  <div class="text-material">Acer</div>
		  <%= image_tag "material_acer.jpg", class: "imatge-material" %>
		</div>
		<div id="material-3" class="requadre-material">
			<div class="text-material">Formigó</div>
			<%= image_tag "material_formigo.jpg", class: "imatge-material" %>
		</div>
		<div id="material-4" class="requadre-material">
			<div class="text-material">Maons</div>
			<%= image_tag "material_maons.jpg", class: "imatge-material" %>
		</div>
		<div id="material-5" class="requadre-material">
			<div class="text-material">Palla</div>
			<%= image_tag "material_palla.jpg", class: "imatge-material" %>
		</div>
		<div id="material-6" class="requadre-material">
			<div class="text-material">Fusta</div>
			<%= image_tag "material_fusta.jpg", class: "imatge-material" %>
		</div>

		<div class="container-casa-material-clear"></div>

		<div id="material-7" class="requadre-material">
			<div class="text-material">Feltre</div>
			<%= image_tag "material_feltre.jpg", class: "imatge-material" %>
		</div>
		<div id="material-8" class="requadre-material">
			<div class="text-material">Terra</div>
			<%= image_tag "material_terra.jpg", class: "imatge-material" %>
		</div>
		<div id="material-9" class="requadre-material">
			<div class="text-material">Pedra</div>
			<%= image_tag "material_pedra.jpg", class: "imatge-material" %>
		</div>
		<div id="material-10" class="requadre-material">
			<div class="text-material">Gel</div>
			<%= image_tag "material_gel.jpg", class: "imatge-material" %>
		</div>
		<div id="material-11" class="requadre-material">
			<div class="text-material">Plàstic</div>
			<%= image_tag "material_plastic.jpg", class: "imatge-material" %>
		</div>
	</div>
</div>

app/views/fases/_vuitena.html.erb
<div id="container-fase-8" class="container-fase">
	<h1 class="titol-repte">La frase amagada</h1>
	<p>Mou les fitxes per resoldre el trencaclosques i troba la frase amagada:</p>
	<ul id="sortable">
	  <li><%= image_tag "puzzle_06.jpg", class: "puzzle-slice", id: "puzzle6" %></li>
	  <li><%= image_tag "puzzle_02.jpg", class: "puzzle-slice", id: "puzzle2" %></li>
	  <li><%= image_tag "puzzle_05.jpg", class: "puzzle-slice", id: "puzzle5" %></li>
	  <li><%= image_tag "puzzle_04.jpg", class: "puzzle-slice", id: "puzzle4" %></li>
	  <li><%= image_tag "puzzle_03.jpg", class: "puzzle-slice", id: "puzzle3" %></li>
	  <li><%= image_tag "puzzle_01.jpg", class: "puzzle-slice", id: "puzzle1" %></li>
	</ul>
	<div class="container-clear"></div>
	<br/>
	<p class="text-repte">Escriu la resposta aquí:</p>
  <input id="input-repte-8"></input>
  <button id="comprova-repte-8" class="btn boto-accio">Comprova</button>
  <p class="benfet8">Correcte!</p>
  <p class="malfet8">No és correcte</p>
</div>

app/views/fases/canvi_fase.html.erb
<div class="row">
  <div class="col-md-8">
  	<p><%= link_to "Fase 1", fases_canvi_fase_path(fase: '1') %>: Les lletres perdudes</p>
  	<p><%= link_to "Fase 2", fases_canvi_fase_path(fase: '2') %>: On és l'illa de Pasqua</p>
  	<p><%= link_to "Fase 3", fases_canvi_fase_path(fase: '3') %>: De què estan fetes les cases</p>
  	<p><%= link_to "Fase 4", fases_canvi_fase_path(fase: '4') %>: Els tres porquets</p>
  	<p><%= link_to "Fase 5", fases_canvi_fase_path(fase: '5') %>: Estufa o manta</p>
  	<p><%= link_to "Fase 8", fases_canvi_fase_path(fase: '8') %>: Puzzle la frase amagada</p>
  	<p><%= link_to "Fase 10", fases_canvi_fase_path(fase: '10') %>: Tria la teva aventura</p>

  	<p><%= link_to "Amagar-ho tot", fases_canvi_fase_path(fase: '0') %></p>
  </div>
</div>

app/views/home/index.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="video-container">
      <div id="wowza_player" style="display:none;"></div>
      <video id="el-video" controls></video>
    </div>
    <div class="container-interactiu">

      <%= render 'fases/primera' %>
      <%= render 'fases/segona' %>
      <%= render 'fases/tercera' %>
      <%= render 'fases/quarta' %>
      <%= render 'fases/cinquena' %>
      <%= render 'fases/vuitena' %>
      <%= render 'fases/desena' %>

    </div>
  </div>
  <div class="col-md-4">
  	<div class="contenidor-xat">
  		<div class="contingut-xat" id="missatges">

  		</div>
  		<div class="form-xat">
				<%= form_for @missatge, remote: true do |f| %>
				  <%= f.hidden_field :user_id, value: current_user.id %>
				  <div class="form-content">
				  	<%= f.text_field :contingut, class: 'field-xat' %>
				  </div>
				  <div class="form-submit">
						<%= f.submit 'Xat', class: 'btn boto-accio', id: 'botodelxat' %>
					</div>
	      <% end %>
  		</div>
  	</div>
  	<div class="contenidor-usuaris">
  		<div class="contenidor-titol">
  			EQUIP
  		</div>
      <div id="online-users">
			  <%= render partial: "users/online", collection: User.online, as: :user %>
			</div>
		</div>
  </div>
</div>


<script>
  (function(){
    var playbackId = "<%= @video %>";
    var url = "https://stream.mux.com/"+playbackId+".m3u8";

    if (Hls.isSupported()) {
      var video = document.getElementById("el-video");
      var hls = new Hls();
      hls.loadSource(url);
      hls.attachMedia(video);
    }
  })();
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Euronet 50/50 online</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag '//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/le-frog/jquery-ui.min.css' %>
    <%= javascript_pack_tag 'fases' %>
    <script src="https://cdn.jsdelivr.net/npm/hls.js@0.8.2"></script>
    
  
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Construaventura</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag '//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/le-frog/jquery-ui.min.css' %>
    <%= javascript_pack_tag 'fases' %>
    <script src="https://cdn.jsdelivr.net/npm/hls.js@0.8.2"></script>
  
  </head>

  <body>
    <div class="continguts-registre">
      <div class="container">
        <%= yield %>
      </div>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/enblanc.html.erb
<%= yield %>

app/views/missatges/edit.html.erb
<h1>Editing Missatge</h1>

<%= render 'form', missatge: @missatge %>

<%= link_to 'Show', @missatge %> |
<%= link_to 'Back', missatges_path %>

app/views/missatges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Missatges</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Contingut</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @missatges.each do |missatge| %>
      <tr>
        <td><%= missatge.user_id %></td>
        <td><%= missatge.contingut %></td>
        <td><%= link_to 'Show', missatge %></td>
        <td><%= link_to 'Edit', edit_missatge_path(missatge) %></td>
        <td><%= link_to 'Destroy', missatge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Missatge', new_missatge_path %>

app/views/missatges/new.html.erb
<h1>New Missatge</h1>

<%= render 'form', missatge: @missatge %>

<%= link_to 'Back', missatges_path %>

app/views/missatges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @missatge.user_id %>
</p>

<p>
  <strong>Contingut:</strong>
  <%= @missatge.contingut %>
</p>

<%= link_to 'Edit', edit_missatge_path(@missatge) %> |
<%= link_to 'Back', missatges_path %>

app/views/shared/_footer.html.erb
<footer>
	<div class="footer-container">
		©2020 Diputació de Barcelona
	</div>
</footer>

app/views/users/_online.html.erb
<div class="item-usuari" data-id="<%= user.id %>">
	<div class="indicador-usuari-online"></div><%= user.name %><div id="check-usuari-<%= user.id %>"></div>
</div>